config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tweets#index'
  resources :tweets
  post   '/like/:tweet_id' => 'likes#like',   as: 'like'
  delete '/like/:tweet_id' => 'likes#unlike', as: 'unlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet, counter_cache: :likes_count
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :likes, dependent: :destroy
  has_many :like_tweets, through: :likes, source: :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(tweet_id: @tweet.id)
    like.save
    redirect_to root_path
  end

  def unlike
    like = current_user.likes.find_by(tweet_id: @tweet.id)
    like.destroy
    redirect_to root_path
  end

  private

  def set_variables
    @tweet = Tweet.find(params[:tweet_id])
    @id_name = "#like-link-#{@tweet.id}"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.page(params[:page]).per(5).order(created_at: :DESC)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      flash[:notice] = "投稿が完了しました"
      redirect_to :root
    else
      flash[:alert] = "ひとことを入力してください"
      render 'new'
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    tweet.update(tweet_params)
    flash[:notice] = "編集が完了しました"
    redirect_to :root
  end

  def destroy
    Tweet.destroy(params[:id] )
    redirect_to :root
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_body.html.haml
%body.body
  .tweets
    - tweets.each do |tweet|
      .tweets__tweet
        .tweets__tweet__top
          .tweets__tweet__top--name
            = tweet.user.name
          .tweets__tweet__top--date
            .tweets__tweet__top--date--text
              = tweet.created_at.strftime("%Y-%m-%d %H:%M")
        .tweets__tweet__body
          = simple_format(tweet.body)
          .tweets__tweet__bottom
            = render 'likes/like', tweet: tweet
            - if user_signed_in? && tweet.user_id == current_user.id
              = link_to "編集", edit_tweet_path(tweet.id), class: 'tweets__tweet__bottom--edit btn'
              = link_to "削除", tweet_path(tweet.id), method: :delete, class: 'tweets__tweet__bottom--deleat btn'
    .pagination-bottom
      = paginate @tweets

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WordDiary
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css", :rel => "stylesheet"}/
  %body
    = render partial: "layouts/flash"
    = yield

app/views/likes/_like.html.erb
<div class="like-link" id="like-link-<%= tweet.id %>">
  <% if user_signed_in? && current_user.likes.find_by(tweet_id: tweet.id) %>
    <%= link_to unlike_path(tweet.id), method: :delete, remote: true do %>
        <div class = "iine__button">❤<%= tweet.likes.count %></div>
    <% end %>
  <% else %>
    <%= link_to like_path(tweet.id), method: :post, remote: true do %>
        <div class = "iine__button">♡️<%= tweet.likes.count %></div>
    <% end %>
  <% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", story: @story  )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", story: @story  )) %>');

app/views/tweets/edit.html.haml
%header.header
  .header__title
    %p ひとこと日記
%body.post
  = form_for @tweet do |f|
    .post__top
      .post__top__title 投稿画面
    .post__center
      = f.label :body, "ひとこと"
      = f.text_area :body, class: "post__center__body", placeholder: "ひとことを入力してください"
    .post__bottom
      = f.submit "投稿する"
%footer.footer

app/views/tweets/index.html.haml
%header.header
  .header__title
    %p ひとこと日記
  .header__link
    - if user_signed_in?
      = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header__link__mypage'
      = link_to "投稿する", new_tweet_path, class: 'header__link__post'
    - else
      = link_to "新規登録", new_user_registration_path,class: 'header__link__mypage'
      = link_to "ログイン", new_user_session_path, class: 'header__link__post'

= render partial: "layouts/body", locals: { tweets: @tweets}, as: :tweet

app/views/tweets/new.html.haml
%header.header
  .header__title
    %p ひとこと日記
  .header__link
%body.body-post
  .post
    = form_for @tweet do |f|
      .post__top
        .post__top__title 投稿する
      .post__center
        = f.label :body, "ひとこと", class: "post__center__label"
        = f.text_area :body, class: "post__center__body", placeholder: "ひとことを入力してください"
      .post__bottom
        .post__bottom__cancel
          = link_to "キャンセル", root_path
        = f.submit "投稿する", class: "post__bottom__submit btn"
%footer.footer